name = "ttm"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNDMxYmU5Y2EtMzQyNi00NjUxLThhNzMtOTk3MjhmYWQ3YmFkIiwidGVuYW50X2lkIjoiMDI3MTBlMDViOGNjN2NmYWVjMzdlNjBjZmFiNTE3YjY4YTNjNDRjMjE2M2E4Yzc1MjJjMGI1NmVlMTExYWNlYyIsImludGVybmFsX3NlY3JldCI6Ijc1NWQwYWNlLThlZjctNDA4MS1iZTM0LTMxMzcyZjhhZjgyZCJ9.CnF6byXfqFlno-in38PlPIHhkS24bpn6bcW_4OuUxVs"

